INSERT INTO TipoUsuario (nombre) VALUES 
    ('Adminstrador'),
    ('Reclutador'),
    ('Desarrollador');

INSERT INTO EstadoInvitacion (nombre) VALUES 
    ('Enviada'),
    ('Aceptada'),
    ('Rechazada');

INSERT INTO CategoriaHabilidad (nombre) VALUES 
    ('Programación'),
    ('Lenguajes'),
    ('Bases de Datos'),
    ('Frameworks'),
    ('Sistemas Operativos'),
    ('Tecnologías'),
    ('Habilidades blandas'),
    ('Idiomas');

INSERT INTO Habilidad (idCategoriaHabilidad, nombre) VALUES 
    (1, 'Front-end'),
    (1, 'Back-end'),
    (1, 'Escritorio'),
    (1, 'Movil'),
    (2, 'PHP'),
    (2, 'Java'),
    (2, 'JavaScript'),
    (2, 'Python'),
    (2, 'C#'),
    (2, 'Typescript'),
    (2, 'Haskell'),
    (2, 'C'),
    (2, 'C++'),
    (2, 'Assembler'),
    (2, 'Bash'),
    (2, 'Swift'),
    (2, 'Visual Basic'),
    (2, 'Kotlin'),
    (2, 'R'),
    (2, 'Objective-C'),
    (2, 'Matlab'),
    (2, 'Go'),
    (2, 'Rust'),
    (2, 'Scala'),
    (2, 'Prolog'),
    (2, 'COBOL'),
    (2, 'Ruby'),
    (2, 'Pascal'),
    (3, 'MySQL'),
    (3, 'Oracle Database'),
    (3, 'PostgreSQL'),
    (3, 'Microsoft SQL Server'),
    (3, 'MariaDB'),
    (3, 'SQLite'),
    (3, 'H2'),
    (3, 'MongoDB'),
    (3, 'Firebase Realtime Database'),
    (4, 'Laravel'),
    (4, 'React Native'),
    (4, 'Angular'),
    (4, 'Django'),
    (4, 'Ionic'),
    (4, 'Xamarin'),
    (4, 'Flutter'),
    (4, 'Spring'),
    (4, 'Express.js'),
    (4, 'JUnit'),
    (5, 'Windows'),
    (5, 'Linux'),    
    (5, 'MacOS'),
    (5, 'Android'),
    (5, 'iOS'),
    (6, 'Docker'),
    (6, 'Kubernetes'),
    (6, 'Jenkins'),
    (6, 'Git'),
    (6, 'Node.js'),
    (6, 'Amazon Web Services'),
    (6, 'Heroku'),
    (7, 'Comunicación'),
    (7, 'Paciencia'),
    (7, 'Trabajo en equipo'),
    (7, 'Trabajo bajo presión'),
    (7, 'Resolución de problemas'),
    (7, 'Adaptación al cambio'),
    (7, 'Toma de decisiones'),
    (7, 'Aprendizaje activo'),
    (8, 'Inglés'),
    (8, 'Español'),
    (8, 'Francés');